image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
tasks:
  - init: pip3 install -r requirements.txt
    command: python3 art.py
